Repository spectrocloud/CanvOS, pull requests merged in 2023-10, with the labels that each got.

#67 PE-2558: use fips image for rke2 if fips_enabled is true
  Earthfile
Labels: auto-backport, backport-release-4.0

#72 PE-2796 fix build opensuse image in proxy env
  .gitignore
  Earthfile
  earthly.sh
Labels: auto-backport, backport-v410-alpha1

#74 fix typo
  earthly.sh
Labels: auto-backport, backport-v410-alpha1

#76 add targetarch
  Earthfile
Labels: auto-backport, backport-v410-alpha1

#81 copy apparmor to /usr/bin and update provider/pe versions
  Earthfile
  README.md
Labels: auto-backport, backport-v410-alpha1

#90 PE-2954 change alpine image
  Earthfile
Labels: auto-backport, backport-release-4.1
